
[functions.handle_stripe_webhook]
enabled = true
verify_jwt = true
import_map = "./functions/handle_stripe_webhook/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/handle_stripe_webhook/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/handle_stripe_webhook/*.html" ]

[functions.create_refund]
enabled = true
verify_jwt = true
import_map = "./functions/create_refund/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create_refund/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create_refund/*.html" ]
